apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata: 
        name: web-pod
        labels:
          env: production
    spec:
      containers:
        - name: "web-container"
          image: "shadowx01/kube-httpd:latest" 